#!/usr/bin/env python3

import skilstak.colors as c
try:
    while True:
        print(c.base02 + "Spooky" + c.base0 + " Scary" + c.base3 + " Skeletons" + c.x, end=" ")

except KeyboardInterrupt:
    exit()

